### ISSUE TITLE
Issues getting it all running

### ISSUE THREAD

**Issue by simonv3** [theodi/quirkafleeg#36]
Hey all

I'm having some issues getting the system running.

After doing some wrangling with rvm, I got the script doing the right thing, but towards the end I'm stumbling across these errors:

```
Generating application keys for panopticon
rake aborted!
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '2-signin' for key 'index_supported_permissions_on_application_id_and_name': INSERT INTO `supported_permissions` (`application_id`, `created_at`, `delegatable`, `name`, `updated_at`) VALUES (2, '2015-03-11 09:03:52', 0, 'signin', '2015-03-11 09:03:52')
...
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:15:in `block (3 levels) in <top (required)>'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `each'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `block (2 levels) in <top (required)>'
```

This happens a couple more times:

```
Generating application keys for publisher
rake aborted!
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '3-signin' for key 'index_supported_permissions_on_application_id_and_name': INSERT INTO `supported_permissions` (`application_id`, `created_at`, `delegatable`, `name`, `updated_at`) VALUES (3, '2015-03-11 09:03:59', 0, 'signin', '2015-03-11 09:03:59')
...
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:15:in `block (3 levels) in <top (required)>'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `each'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `block (2 levels) in <top (required)>'
```
```
Generating application keys for asset-manager
rake aborted!
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '4-signin' for key 'index_supported_permissions_on_application_id_and_name': INSERT INTO `supported_permissions` (`application_id`, `created_at`, `delegatable`, `name`, `updated_at`) VALUES (4, '2015-03-11 09:04:05', 0, 'signin', '2015-03-11 09:04:05')
...
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:15:in `block (3 levels) in <top (required)>'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `each'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `block (2 levels) in <top (required)>'
```
```
Generating application keys for contentapi
rake aborted!
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '5-signin' for key 'index_supported_permissions_on_application_id_and_name': INSERT INTO `supported_permissions` (`application_id`, `created_at`, `delegatable`, `name`, `updated_at`) VALUES (5, '2015-03-11 09:04:12', 0, 'signin', '2015-03-11 09:04:12')
...
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:15:in `block (3 levels) in <top (required)>'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `each'
/Users/simon/src/quirkafleeg/signon/lib/tasks/applications.rake:14:in `block (2 levels) in <top (required)>'
```

Then a bit further down the script (cause it continues):

```
Generating content-api bearer tokens for frontends
rake aborted!
ArgumentError: Unsupported permission 'access_unpublished'
/Users/simon/src/quirkafleeg/signon/lib/tasks/api_clients.rake:21:in `block (2 levels) in <top (required)>'
```

And then it completes.

I can use the generated users urls to sign in to signon.dev, but any other application doesn't seem to work.

When I access www.dev I get:

```
GdsApi::EndpointNotFound in RootController#index
Could not connect to https://contentapi.dev/section.json?id=index&role=odi

app/controllers/root_controller.rb:25:in `index'
```

So I go take a look at contentapi.dev and see the Sinatra "Sinatra doesn't know this ditty" error page.

When I access panopticon.dev or publisher.dev, I get redirected to:

```
https://signon.dev/oauth/authorize?client_id=abcdefgh12345678pan&redirect_uri=http%3A%2F%2Fpanopticon.dev%2Fauth%2Fgds%2Fcallback&response_type=code&state=3169c7921aeca5c663fd31870ca0674062ed6393dc4beff9
```
but my browser says it can't find the page.

**Comment by Floppy** [comment]
Hi Simon - thanks for that, it's possible there's some bitrot. I'll run it here and see if I can get the same thing to debug.

**Comment by Floppy** [comment]
@simonv3 One thing - we're switched since this was written from using rvm to rbenv. If we updated the script to use that, would that be very annoying?

**Comment by simonv3** [comment]
@Floppy I actually just laughed out loud. I was using rbenv before this, and decided that it might be worth the effort to switch to rvm (cause so far most people I've talked to use it). So a part of my "wrangling with rvm" was switching to rbenv.

I wouldn't mind at all - I'm more familiar with rbenv than rvm, so I'm happy to figure out switching back.

**Comment by Floppy** [comment]
I thought that might be the case! We decided rvm was too much trouble a little while ago. I'm updating the script now. Sorry for the hassle :)

**Comment by Floppy** [comment]
Good news, I have the above error now, so will fix.

**Comment by simonv3** [comment]
@Floppy Great, thanks! I just want to confirm - what version of ruby are you using for this?

**Comment by Floppy** [comment]
The apps are still ruby 1.9.3

**Comment by Floppy** [comment]
OK, I've pushed a new version which should resolve the issues above, apart from the last two which are caused by incorrect use of HTTPS. Looking at those now...

**Comment by Floppy** [comment]
There is an update to the signonotron2 app as well, but the script should pull that in.

**Comment by simonv3** [comment]
Thanks @Floppy 

I ran the most recent script and it looks like there's a lot less errors on start up. 

Before running the script I get these warnings, I don't know if they're important:

```
cat: ./rackspacecreds: No such file or directory
cat: ./mandrillcreds: No such file or directory
cat: ./juviacreds: No such file or directory
```

I'm getting this error with the current script: 

```
./setup.rb:260:in ``': No such file or directory - RUMMAGER_INDEX=all bundle exec rake rummager:migrate_index (Errno::ENOENT)
	from ./setup.rb:260:in `block in <main>'
	from ./setup.rb:258:in `chdir'
	from ./setup.rb:258:in `<main>'
quirkafleeg$ ./setup.rb 
```
Which I had previously worked around by changing that line in setup.rb to be a system call (as opposed to a backtick). Making the same changes now I end up with no errors, but I don't know whether that's good or not.

I'm still getting the same errors with panopticon and publishers when accessing them (ie, nothing loads). In a last-ditch attempt I removed the s from https and got:

```
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
```

I'm not surprised it didn't work, but just thought I'd add it in case that helps.

contentapi.dev still shows a blank Sinatra page at the root, but when I access:
```
http://contentapi.dev/section.json?id=index&role=odi
```
(note, not HTTPS, but HTTP), I get:

```
NoMethodError: undefined method `assets' for nil:NilClass
~/src/quirkafleeg/contentapi/govuk_content_api.rb:740:in `attach_non_artefact_asset'
~/src/quirkafleeg/contentapi/govuk_content_api.rb:457:in `block in <class:GovUkContentApi>'
```

Let me know if there's anything other information I can provide.

**Comment by Floppy** [comment]
Sounds like we’re about at the same place; I spent yesterday afternoon looking at the HTTPS problem, and it’s very odd. The system shouldn’t be doing that, and I’m not sure why it is. Hopefully I’ll crack it this morning. Also I’ll look at the rummager error too. Thanks for bearing with me :)

**Comment by simonv3** [comment]
Sure thing, thanks so much for taking a look into it!

**Comment by pezholio** [comment]
Hey Simon, we're still not sure why this is happening, something to do with load order - it looks like Plek (which tells the apps where to look for each component) is getting loaded before Dotenv. So for now, try appending:

    export DEV_DOMAIN=dev

To the `.powrc` file in the `www` project, restart pow, and you should be golden :smiley_cat:

**Comment by Floppy** [comment]
We can commit this, it's in the powrc file in the project. Stu is doing that now.

**Comment by pezholio** [comment]
Done! :+1:

**Comment by simonv3** [comment]
Thanks @pezholio and @Floppy 

Unfortunately, I'm still getting the same errors:

Signing in to signon works fine. But when I click on panopticon or publisher, I get sent to this URL (didn't edit the https this time):

```
http://signon.dev/oauth/authorize?client_id=0b4aa833f0ebd6aa0d4df5c32cabd5b02dbef89cdf5722c70fb681c8ceec4912&redirect_uri=http%3A%2F%2Fpublisher.dev%2Fauth%2Fgds%2Fcallback&response_type=code&state=bca6f326d0de4d3b6230e268b3bf09dee7f222b2180d24d7
```

and I see:

```
An error has occurred
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
Signon release: development
```
![screenshot 2015-03-12 20 14 42](https://cloud.githubusercontent.com/assets/485583/6618316/7527cacc-c8f4-11e4-9dcd-b00872b73a5d.png)

**contentapi.dev** fails with:

```
Gem::LoadError: You have already activated dotenv 2.0.0, but your Gemfile requires dotenv 1.0.2. Prepending `bundle exec` to your command may solve this.
~/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.8.5/lib/bundler/runtime.rb:34:in `block in setup'
~/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.8.5/lib/bundler/runtime.rb:19:in `setup'
~/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.8.5/lib/bundler.rb:129:in `setup'
~/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.8.5/lib/bundler.rb:134:in `require'
~/src/quirkafleeg/contentapi/config.ru:14:in `block in <main>'
```

on accessing **asset-manager.dev** I get:

```
Routing Error

No route matches [GET] "/"
Try running rake routes for more information on available routes.
```
This might be normal though, rake routes outputs:

```
                  /media/:id/:filename(.:format)            media#download {:filename=>/.*/}
 healthcheck GET  /healthcheck(.:format)                    #<Proc:0x007f9f9d644288@/Users/simon/src/quirkafleeg/asset-manager/config/routes.rb:6>
 gds_sign_in      /auth/gds/callback(.:format)              authentications#callback
gds_sign_out      /auth/gds/sign_out(.:format)              authentications#sign_out
auth_failure      /auth/failure(.:format)                   authentications#failure
             PUT  /auth/gds/api/users/:uid(.:format)        api/user#update
             POST /auth/gds/api/users/:uid/reauth(.:format) api/user#reauth
```

**contentapi.dev** still returns the empty sinatra page.

**www.dev** now returns:

```
GdsApi::HTTPErrorResponse in RootController#index
[styles information]
<body class="big">
  <div class="page">
    
  <h1 class="err">Error starting application</h1>
  <h2>Your Rack app raised an exception when Pow tried to run it.</h2>
  <section>
    <pre class="breakout small_text"><strong>NoMethodError: undefined method `assets' for nil:NilClass</strong>
~/src/quirkafleeg/contentapi/govuk_content_api.rb:740:in `attach_non_artefact_asset'
~/src/quirkafleeg/contentapi/govuk_content_api.rb:457:in `block in &lt;class:GovUkContentApi&gt;'
~/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
```

Let me know if there's any other information that would be helpful to you. Thanks so much for taking so much time to look into this!

**Comment by simonv3** [comment]
An update:

I deleted everything, and reinstalled pow, and then ran the script again.

I downgraded dotenv to 1.0.2, but then contentapi complains that it needs dotenv 0.0.7. When I downgrade to 0.0.7, publisher and panopticon complained. So I upgraded everything to 2.0.0, and that stopped the complaining about dotenv.

I looked at the oauth_applications that get created in mysql:

```
select * from oauth_applications;
+----+---------------+------------------------------------------------------------------+------------------------------------------------------------------+--------------------------------------------+---------------------+---------------------+--------------------------+---------------------------------+-----------------------+
| id | name          | uid                                                              | secret                                                           | redirect_uri                               | created_at          | updated_at          | home_uri                 | description                     | supports_push_updates |
+----+---------------+------------------------------------------------------------------+------------------------------------------------------------------+--------------------------------------------+---------------------+---------------------+--------------------------+---------------------------------+-----------------------+
|  2 | panopticon    | 38d960d34d9d6fd3faa884e8784fbeec8ab79a85e58ea78a21a456fbad210bd5 | 7d1f48643f26869370574849a4e9774e252d606f58878ff6d049b8094cc1ba82 | http://panopticon.dev/auth/gds/callback    | 2015-03-13 01:25:07 | 2015-03-13 01:25:07 | http://panopticon.dev    | metadata management             |                     1 |
|  3 | publisher     | d75111d7934bd3f38868605c35ce2ee1b8ac9dc382c21ef0017d08be43ec38a2 | 13d38f711a0c73083d89b6ef68232cc031724387acce551ef1394ca729d413a1 | http://publisher.dev/auth/gds/callback     | 2015-03-13 01:25:17 | 2015-03-13 01:25:17 | http://publisher.dev     | content editing                 |                     1 |
|  4 | asset-manager | 5f5180699500edf317d1f67c1c4de3d18d275a6c91b5dc1eb32aa6f83276109e | 0e80e76b21e98c1c718458e00f23c9d6d924f64dc5f8a1656f5357c5bc881554 | http://asset-manager.dev/auth/gds/callback | 2015-03-13 01:25:25 | 2015-03-13 01:25:25 | http://asset-manager.dev | media uploading                 |                     1 |
|  5 | contentapi    | 506f18d24c13200d0532a868cb089a59c6b7ec2173cef71724887de416e8771c | 96d88bb0bbfdddc99072f13e0101b39bfd82d3345a93d6845fd9c42b9064a183 | http://contentapi.dev/auth/gds/callback    | 2015-03-13 01:25:33 | 2015-03-13 01:25:33 | http://contentapi.dev    | internal API for content access |                     1 |
|  6 | frontends     | 76c6eec06972e390248722e81ddf3df1db487b09091ee33ae9b54c8527b5d577 | 6af501d93382c240ac8dddc38299bb0ee939390fa521ef3fe1714fdef269f3db | http://frontends.dev/auth/gds/callback     | 2015-03-13 01:25:56 | 2015-03-13 01:25:56 | http://frontends.dev     | Front end apps                  |                     1 |
+----+---------------+------------------------------------------------------------------+------------------------------------------------------------------+--------------------------------------------+---------------------+---------------------+--------------------------+---------------------------------+-----------------------+
```

And noticed that none of those contain the client_id listed in the callback (for panopticon.dev):

```
http://signon.dev/oauth/authorize?client_id=236a8abcd769a6fff7f1294fe64b359bca3eaaa3378721c24c742892df81d67c&redirect_uri=http%3A%2F%2Fpanopticon.dev%2Fauth%2Fgds%2Fcallback&response_type=code&state=b152b7bff7743ab3679341ac1a7f3250b10933eadb2983f0
```

or (for publisher.dev)

```
http://signon.dev/oauth/authorize?client_id=0b4aa833f0ebd6aa0d4df5c32cabd5b02dbef89cdf5722c70fb681c8ceec4912&redirect_uri=http%3A%2F%2Fpublisher.dev%2Fauth%2Fgds%2Fcallback&response_type=code&state=9ddf4dac1e207284c007ba6ef9a3f627e7ca3efcb0117ea7
```

Simply substituting the client ID in the case of both publisher and panopticon.dev shows me:
```
http://publisher.dev/auth/failure?message=csrf_detected&origin=http%3A%2F%2Fsignon.dev%2F&strategy=gds

Error

There was a problem logging you into the application. Please try again.
```

I could be off here on how oauth works, but that might be an indicator? If either of you have some time in your morning to jump on a call to try and walk through this that might speed things up significantly.

Cheers,
Simon

**Comment by Floppy** [comment]
I've just fixed a couple of bugs and rerun the script from scratch, having dropped the MySQL databases as well, and everything seems to work correctly to a certain point. I can create the user successfully, and log in to panopticon and publisher.

There is still an issue with dotenv when starting contentapi, so I'm looking at that right now. I think we're nearly there though. I suspect that some of your issues with the tokens is down to old data. Can you drop the `signontron2_development` database and try again?

**Comment by Floppy** [comment]
Oh, also, you probably don't need to worry about this missing credential file warnings. Juvia is for comments, Mandrill is for emailing, and rackspace is for asset uploads. I think we'll be OK without them, but if we do need them we'll add them later. There are `.example` files for each of those, which you could copy and remove `.example` if you want the warning to go away :)

**Comment by simonv3** [comment]
I've been dropping the databases (both development and test) every time
before running the script so far, but I'll do it again with some of your
bug fixes.

**Comment by Floppy** [comment]
OK, that's good. It just went through for me, so it seems OK. I'll get @pezholio to check as well.

**Comment by Floppy** [comment]
Working pretty well here now, with a fix to contentapi, and a loaded mongodb backup from the live site.

Mongodb restore command:
```
tar xzvf ~/Downloads/mongo.2015-03-13T02-00-05.tar.bz2
mongorestore --drop -d govuk_content_development tmp/20150313-27263-wht9cp/govuk_content_publisher/
```

**Comment by simonv3** [comment]
Good news!

It looks like www.dev now works, like you said with missing assets, but that's not a huge deal:
![screenshot 2015-03-13 15 17 24](https://cloud.githubusercontent.com/assets/485583/6635067/1a2f0f36-c994-11e4-80f4-09bc3db58760.png)

However, both panopticon and publisher are still returning the 

```
An error has occurred
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
Signon release: development
```
error.

The urls are:

```
http://signon.dev/oauth/authorize?client_id=abcdefgh12345678pan&redirect_uri=http%3A%2F%2Fpanopticon.dev%2Fauth%2Fgds%2Fcallback&response_type=code&state=dc22cdc831b7507716ea9a2160899f5d02c2b16f5eddc0cc
``` and
```
http://signon.dev/oauth/authorize?client_id=abcdefghjasndjkasndpublisher&redirect_uri=http%3A%2F%2Fpublisher.dev%2Fauth%2Fgds%2Fcallback&response_type=code&state=89444886e5105a84efc56be625decd2b90b6ece37f1b8be0
```

Those client IDs look like they're not random.

**Comment by pezholio** [comment]
I'll give this a go now, and see if I can replicate it

**Comment by simonv3** [comment]
@pezholio so far it looks like I got it working. I'll add some details momentarily.

**Comment by pezholio** [comment]
Cool :+1:

**Comment by simonv3** [comment]
I remembered a while ago that I had changed the system call at the end of the script from using a \` to using `system ''`. When I implemented that change - so:

```
Dir.chdir('search') do
  puts green("Creating indices for rummager")
  system 'RUMMAGER_INDEX=all bundle exec rake rummager:migrate_index'
end

system './make_env'
```

and I dumped the database, and re-ran the script, it looks like everything worked.

So presumably something in one of those two lines (or just resetting the database for the x-th time?) caused it all to work. I'm not sure what either of them do, so I'll leave it to someone who knows the system a bit better to figure out.

**Comment by pezholio** [comment]
Awesome :smile:

**Comment by Floppy** [comment]
ooh, crap. The last item is what sticks the environment together and sets all the right keys in the right places, so if that wasn't working, *of course* those client IDs would be wrong. Looks like you cracked it @simonv3 :)

**Comment by pezholio** [comment]
Ah, of course!

**Comment by simonv3** [comment]
Yay!
